version: 1
name: bluestorage
server:
  app: "__main__:app"
  host: "0.0.0.0"
  port: 8000
  log_level: "info"

  # For ssl
  # ssl_keyfile: "./config/key.pem"
  # ssl_certfile: "./config/cert.pem"
DB:
  upload_dir: "./storage/"
  url: "sqlite+aiosqlite:///test.db"
TOKEN:
  expiration_date: 7
