name: CI

on:
  push:
    branches: [main]
    paths-ignore: 
      - '**.md'  
  
  pull_request:
    branches: [main]
    paths-ignore: 
      - '**.md'
  
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup pip and Install dependencies
        run: |
          python -m pip install pip
          pip install -r requirements.txt
      - name: Check type
        run: python -m pytest tests 
  
